import type { GeometryCardinalDirection } from "$root";

export type GlyphKey = |
    `chat-text` |
    `eye` |
    `export` |
    `video-camera` |
    `device-mobile-camera` |
    `crop` |
    `map-trifold` |
    `trash-simple` |
    `backspace` |
    `user-circle-check` |
    `images-square` |
    `bell` |
    `columns` |
    `bold` |
    `article` |
    `grid-four` |
    `link-simple` |
    `seal-check` |
    `selection-foreground` |
    `image-square` |
    `image-broken` |
    `funnel` |
    `users-three` |
    `note-blank` |
    `user-circle-plus` |
    `user-circle` |
    `receipt` |
    `invoice` |
    `note` |
    `arrow-left` |
    `arrows-down-up` |
    `basket` |
    `arrow-right` |
    `upload-simple` |
    `printer` |
    `download-simple` |
    `list` |
    `asterisk` |
    `asterisk-simple` |
    `subtitles-slash` |
    `cardholder` |
    `globe-x` |
    `exclamation-mark` |
    `network-x` |
    `x-circle` |
    `address-book-tabs` |
    `paper-plane-tilt` |
    `note-pencil` |
    `share-fat` |
    `folder` |
    `trash` |
    `plus-circle` |
    `currency-${GlyphKeyCurrency}` |
    `arrow-down` |
    `caret-circle-down` |
    `caret-circle-up` |
    `shopping-bag-open` |
    `coffee-bean` |
    `compass` |
    `map-pin-simple` |
    `handbag-simple` |
    `devices` |
    `lock-key` |
    `gear` |
    `gear-fine` |
    `bell-simple` |
    `envelope` |
    `house-line` |
    `arrows-left-right` |
    `list-plus` |
    `squares-four` |
    `list-plus` |
    `app-window` |
    `circle-notch` |
    `subtract-square` |
    `device-tablet-speaker` |
    `weather-cloud` |
    `warning` |
    `circle-notch` |
    `minus` |
    `key` |
    `arrow-u-up-left` |
    `arrow-counter-clockwise` |
    `circle` |
    `check-circle` |
    `circle-dashed` |
    `dots-three` |
    `cards-three` |
    `lightning` |
    `cards` |
    `note-pencil` |
    `tray` |
    `calendar-dots` |
    `notepad` |
    `network` |
    `calendar-blank` |
    `chats-circle` |
    `plant` |
    `farm` |
    `magnifying-glass` |
    `chat-circle-dots` |
    `dots-three-outline` |
    `copy` |
    `circles-four` |
    `waveform` |
    `film-strip` |
    `arrow-up` |
    `arrow-circle-up` |
    `plus` |
    `funnel-simple` |
    `user` |
    `camera` |
    `check` |
    `file` |
    `share-network` |
    `question` |
    `minus-circle` |
    `globe-simple` |
    `globe` |
    `warning-circle` |
    `x` |
    `info` |
    `caret-${GeometryCardinalDirection}` |
    `caret-up-down`;

export type GlyphKeyCurrency = `dollar` | `eur`;
export type GlyphWeight = `bold` | `fill`
