

export type IClientDatabase<
    TILocationGcsCreate extends object,
    TLocationGcsCreateResolve extends object,
    TILocationGcsRead extends object,
    TLocationGcsReadResolve extends object,
    TILocationGcsReadList extends object,
    TLocationGcsReadListResolve extends object,
    TILocationGcsDelete extends object,
    TLocationGcsDeleteResolve extends object,
    TILocationGcsUpdate extends object,
    TLocationGcsUpdateResolve extends object,
    TITradeProductCreate extends object,
    TTradeProductCreateResolve extends object,
    TITradeProductRead extends object,
    TTradeProductReadResolve extends object,
    TITradeProductReadList extends object,
    TTradeProductReadListResolve extends object,
    TITradeProductDelete extends object,
    TTradeProductDeleteResolve extends object,
    TITradeProductUpdate extends object,
    TTradeProductUpdateResolve extends object,
    TINostrProfileCreate extends object,
    TNostrProfileCreateResolve extends object,
    TINostrProfileRead extends object,
    TNostrProfileReadResolve extends object,
    TINostrProfileReadList extends object,
    TNostrProfileReadListResolve extends object,
    TINostrProfileDelete extends object,
    TNostrProfileDeleteResolve extends object,
    TINostrProfileUpdate extends object,
    TNostrProfileUpdateResolve extends object,
    TINostrRelayCreate extends object,
    TNostrRelayCreateResolve extends object,
    TINostrRelayRead extends object,
    TNostrRelayReadResolve extends object,
    TINostrRelayReadList extends object,
    TNostrRelayReadListResolve extends object,
    TINostrRelayDelete extends object,
    TNostrRelayDeleteResolve extends object,
    TINostrRelayUpdate extends object,
    TNostrRelayUpdateResolve extends object,
    TIMediaImageCreate extends object,
    TMediaImageCreateResolve extends object,
    TIMediaImageRead extends object,
    TMediaImageReadResolve extends object,
    TIMediaImageReadList extends object,
    TMediaImageReadListResolve extends object,
    TIMediaImageDelete extends object,
    TMediaImageDeleteResolve extends object,
    TIMediaImageUpdate extends object,
    TMediaImageUpdateResolve extends object,
    TILogErrorCreate extends object,
    TLogErrorCreateResolve extends object,
    TILogErrorRead extends object,
    TLogErrorReadResolve extends object,
    TILogErrorReadList extends object,
    TLogErrorReadListResolve extends object,
    TILogErrorDelete extends object,
    TLogErrorDeleteResolve extends object,
    TILogErrorUpdate extends object,
    TLogErrorUpdateResolve extends object
> = {
    location_gcs_create(opts: TILocationGcsCreate): Promise<TLocationGcsCreateResolve>; 
    location_gcs_read(opts: TILocationGcsRead): Promise<TLocationGcsReadResolve>; 
    location_gcs_read_list(opts: TILocationGcsReadList): Promise<TLocationGcsReadListResolve>; 
    location_gcs_delete(opts: TILocationGcsDelete): Promise<TLocationGcsDeleteResolve>; 
    location_gcs_update(opts: TILocationGcsUpdate): Promise<TLocationGcsUpdateResolve>; 
    trade_product_create(opts: TITradeProductCreate): Promise<TTradeProductCreateResolve>; 
    trade_product_read(opts: TITradeProductRead): Promise<TTradeProductReadResolve>; 
    trade_product_read_list(opts: TITradeProductReadList): Promise<TTradeProductReadListResolve>; 
    trade_product_delete(opts: TITradeProductDelete): Promise<TTradeProductDeleteResolve>; 
    trade_product_update(opts: TITradeProductUpdate): Promise<TTradeProductUpdateResolve>; 
    nostr_profile_create(opts: TINostrProfileCreate): Promise<TNostrProfileCreateResolve>; 
    nostr_profile_read(opts: TINostrProfileRead): Promise<TNostrProfileReadResolve>; 
    nostr_profile_read_list(opts: TINostrProfileReadList): Promise<TNostrProfileReadListResolve>; 
    nostr_profile_delete(opts: TINostrProfileDelete): Promise<TNostrProfileDeleteResolve>; 
    nostr_profile_update(opts: TINostrProfileUpdate): Promise<TNostrProfileUpdateResolve>; 
    nostr_relay_create(opts: TINostrRelayCreate): Promise<TNostrRelayCreateResolve>; 
    nostr_relay_read(opts: TINostrRelayRead): Promise<TNostrRelayReadResolve>; 
    nostr_relay_read_list(opts: TINostrRelayReadList): Promise<TNostrRelayReadListResolve>; 
    nostr_relay_delete(opts: TINostrRelayDelete): Promise<TNostrRelayDeleteResolve>; 
    nostr_relay_update(opts: TINostrRelayUpdate): Promise<TNostrRelayUpdateResolve>; 
    media_image_create(opts: TIMediaImageCreate): Promise<TMediaImageCreateResolve>; 
    media_image_read(opts: TIMediaImageRead): Promise<TMediaImageReadResolve>; 
    media_image_read_list(opts: TIMediaImageReadList): Promise<TMediaImageReadListResolve>; 
    media_image_delete(opts: TIMediaImageDelete): Promise<TMediaImageDeleteResolve>; 
    media_image_update(opts: TIMediaImageUpdate): Promise<TMediaImageUpdateResolve>; 
    log_error_create(opts: TILogErrorCreate): Promise<TLogErrorCreateResolve>; 
    log_error_read(opts: TILogErrorRead): Promise<TLogErrorReadResolve>; 
    log_error_read_list(opts: TILogErrorReadList): Promise<TLogErrorReadListResolve>; 
    log_error_delete(opts: TILogErrorDelete): Promise<TLogErrorDeleteResolve>; 
    log_error_update(opts: TILogErrorUpdate): Promise<TLogErrorUpdateResolve>; 
}; 